name: dfe-flexforms

networks:
    dfe-flexforms-network:
        name: dfe-flexforms-network
        driver: bridge
        external: true

services:
    ea_api:
        container_name: ea-flexforms-api
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        build:
            context: ${REPO_PATH}
            dockerfile: Dockerfile.dev
        ports:
            - 5277:8080
            - 7089:8081
        restart: unless-stopped
        environment:
            - ConnectionStrings__DefaultConnection=Server=sql,1433;Database=ExternalApplications;User Id=SA;Password=Pa55w0rd!;TrustServerCertificate=True;
            - ConnectionStrings__TenantConfigDatabase=Server=sql,1433;Database=TenantConfig;User Id=SA;Password=Pa55w0rd!;TrustServerCertificate=True;
            - ConnectionStrings__Redis=redis:6379
            - CacheSettings__Redis__ConnectionString=redis:6379
            - DataProtection__UseAzure=false
            - DataProtection__UseStorageSas=false
            - Tenants__CodeGeneration__ConnectionStrings__Redis=redis:6379
            - ASPNETCORE_URLS=https://+:8081;http://+:8080
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Pa55w0rd
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ea_cert.pfx
            #- CI=true 
        volumes:
            - ${APPDATA}/dev-certs/ea_cert.pfx:/https/ea_cert.pfx:ro
            - ${APPDATA}/Microsoft/UserSecrets/f714ca7a-fc08-46ff-b0cc-373d6f04cf4c:/home/app/.microsoft/usersecrets/f714ca7a-fc08-46ff-b0cc-373d6f04cf4c:ro
            - ${APPDATA}/mkcert/rootCA.pem:/usr/local/share/ca-certificates/mkcert-rootCA.crt:ro
        networks:
            - dfe-flexforms-network